defaults:
  tiered_equipment: &TIERED_EQUIPMENT
    mode: TIERED
    tier_min: 4
    tier_max: 8
    ench_min: 0
    ench_max: 4
    qualities: [1, 2, 3, 4, 5]

template_groups:
  # Armas
  - name: hachas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/hachas]
    template_keys:
      - MAIN_AXE
      - 2H_AXE
      - 2H_HALBERD
      - 2H_HALBERD_MORGANA
      - 2H_SCYTHE_HELL
      - 2H_DUALAXE_KEEPER
      - 2H_AXE_AVALON
      - 2H_SCYTHE_CRYSTAL

  - name: espadas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/espadas]
    template_keys:
      - MAIN_SWORD
      - 2H_CLAYMORE
      - 2H_DUALSWORD
      - MAIN_SCIMITAR_MORGANA
      - 2H_CLEAVER_HELL
      - 2H_DUALSCIMITAR_UNDEAD
      - 2H_CLAYMORE_AVALON
      - MAIN_SWORD_CRYSTAL

  - name: mazas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/mazas]
    template_keys:
      - MAIN_MACE
      - 2H_MACE
      - 2H_FLAIL
      - MAIN_ROCKMACE_KEEPER
      - MAIN_MACE_HELL
      - 2H_MACE_MORGANA
      - 2H_DUALMACE_AVALON
      - MAIN_MACE_CRYSTAL

  - name: martillos
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/martillos]
    template_keys:
      - MAIN_HAMMER
      - 2H_POLEHAMMER
      - 2H_HAMMER
      - 2H_HAMMER_UNDEAD
      - 2H_DUALHAMMER_HELL
      - 2H_RAM_KEEPER
      - 2H_HAMMER_AVALON
      - 2H_HAMMER_CRYSTAL

  - name: guantes_de_guerra
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/guantes-de-guerra]
    template_keys:
      - 2H_IRONGAUNTLETS_HELL
      - 2H_KNUCKLES_SET1
      - 2H_KNUCKLES_SET2
      - 2H_KNUCKLES_SET3
      - 2H_KNUCKLES_KEEPER
      - 2H_KNUCKLES_HELL
      - 2H_KNUCKLES_MORGANA
      - 2H_KNUCKLES_AVALON
      - 2H_KNUCKLES_CRYSTAL

  - name: ballestas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/ballestas]
    template_keys:
      - 2H_CROSSBOW
      - 2H_CROSSBOWLARGE
      - MAIN_1HCROSSBOW
      - 2H_REPEATINGCROSSBOW_UNDEAD
      - 2H_DUALCROSSBOW_HELL
      - 2H_CROSSBOWLARGE_MORGANA
      - 2H_CROSSBOW_CANNON_AVALON
      - 2H_DUALCROSSBOW_CRYSTAL

  - name: arcos
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/arcos]
    template_keys:
      - 2H_BOW
      - 2H_WARBOW
      - 2H_LONGBOW
      - 2H_LONGBOW_UNDEAD
      - 2H_BOW_HELL
      - 2H_BOW_KEEPER
      - 2H_BOW_AVALON
      - 2H_BOW_CRYSTAL

  - name: dagas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/dagas]
    template_keys:
      - MAIN_DAGGER
      - 2H_DAGGERPAIR
      - 2H_CLAWPAIR
      - MAIN_RAPIER_MORGANA
      - MAIN_DAGGER_HELL
      - DUALSICKLE_UNDEAD
      - DAGGER_KATAR_AVALON
      - DAGGERPAIR_CRYSTAL

  - name: lanzas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/lanzas]
    template_keys:
      - MAIN_SPEAR
      - 2H_SPEAR
      - 2H_GLAIVE
      - MAIN_SPEAR_KEEPER
      - 2H_HARPOON_HELL
      - 2H_TRIDENT_UNDEAD
      - MAIN_SPEAR_LANCE_AVALON
      - 2H_GLAIVE_CRYSTAL

  - name: varas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/varas]
    template_keys:
      - 2H_QUARTERSTAFF
      - 2H_IRONCLADEDSTAFF
      - 2H_DOUBLEBLADEDSTAFF
      - 2H_COMBATSTAFF_MORGANA
      - 2H_TWINSCYTHE_HELL
      - 2H_ROCKSTAFF_KEEPER
      - QUARTERSTAFF_AVALON
      - 2H_DOUBLEBLADEDSTAFF_CRYSTAL

  - name: cambiaformas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/cambiaformas]
    template_keys:
      - 2H_SHAPESHIFTER_SET1
      - 2H_SHAPESHIFTER_SET2
      - 2H_SHAPESHIFTER_SET3
      - 2H_SHAPESHIFTER_MORGANA
      - 2H_SHAPESHIFTER_HELL
      - 2H_SHAPESHIFTER_KEEPER
      - 2H_SHAPESHIFTER_AVALON
      - 2H_SHAPESHIFTER_CRYSTAL

  # Bastones
  - name: bastones_naturales
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/bastones/naturales]
    template_keys:
      - MAIN_NATURESTAFF
      - 2H_NATURESTAFF
      - 2H_WILDSTAFF
      - MAIN_NATURESTAFF_KEEPER
      - 2H_NATURESTAFF_HELL
      - 2H_NATURESTAFF_KEEPER  # duplicado segÃºn la lista que enviaste
      - MAIN_NATURESTAFF_AVALON
      - MAIN_NATURESTAFF_CRYSTAL

  - name: bastones_fuego
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/bastones/fuego]
    template_keys:
      - MAIN_FIRESTAFF
      - 2H_FIRESTAFF
      - 2H_INFERNOSTAFF
      - MAIN_FIRESTAFF_KEEPER
      - 2H_FIRESTAFF_HELL
      - 2H_INFERNOSTAFF_MORGANA
      - 2H_FIRE_RINGPAIR_AVALON
      - MAIN_FIRESTAFF_CRYSTAL

  - name: bastones_sagrados
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/bastones/sagrados]
    template_keys:
      - MAIN_HOLYSTAFF
      - 2H_HOLYSTAFF
      - 2H_DIVINESTAFF
      - MAIN_HOLYSTAFF_MORGANA
      - 2H_HOLYSTAFF_HELL
      - 2H_HOLYSTAFF_UNDEAD
      - MAIN_HOLYSTAFF_AVALON
      - 2H_HOLYSTAFF_CRYSTAL

  - name: bastones_arcanos
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/bastones/arcanos]
    template_keys:
      - MAIN_ARCANESTAFF
      - 2H_ARCANESTAFF
      - 2H_ENIGMATICSTAFF
      - MAIN_ARCANESTAFF_UNDEAD
      - 2H_ARCANESTAFF_HELL
      - 2H_ENIGMATICORB_MORGANA
      - 2H_ARCANE_RINGPAIR_AVALON
      - 2H_ARCANESTAFF_CRYSTAL

  - name: bastones_hielo
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/bastones/hielo]
    template_keys:
      - MAIN_FROSTSTAFF
      - 2H_FROSTSTAFF
      - 2H_GLACIALSTAFF
      - MAIN_FROSTSTAFF_KEEPER
      - 2H_ICEGAUNTLETS_HELL
      - 2H_ICECRYSTAL_UNDEAD
      - MAIN_FROSTSTAFF_AVALON
      - 2H_FROSTSTAFF_CRYSTAL

  - name: bastones_malditos
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/bastones/malditos]
    template_keys:
      - MAIN_CURSEDSTAFF
      - 2H_CURSEDSTAFF
      - 2H_DEMONICSTAFF
      - MAIN_CURSEDSTAFF_UNDEAD
      - 2H_SKULLORB_HELL
      - 2H_CURSEDSTAFF_MORGANA
      - MAIN_CURSEDSTAFF_AVALON
      - MAIN_CURSEDSTAFF_CRYSTAL

  # Armadura - Tela
  - name: tunicas_tela
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/tela/tunicas]
    template_keys:
      - ARMOR_CLOTH_SET1
      - ARMOR_CLOTH_SET2
      - ARMOR_CLOTH_SET3
      - ARMOR_CLOTH_KEEPER
      - ARMOR_CLOTH_HELL
      - ARMOR_CLOTH_MORGANA
      - ARMOR_CLOTH_FEY
      - ARMOR_CLOTH_AVALON
      - ARMOR_CLOTH_ROYAL

  - name: habitos_tela
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/tela/habitos]
    template_keys:
      - HEAD_CLOTH_SET1
      - HEAD_CLOTH_SET2
      - HEAD_CLOTH_SET3
      - HEAD_CLOTH_KEEPER
      - HEAD_CLOTH_HELL
      - HEAD_CLOTH_MORGANA
      - HEAD_CLOTH_FEY
      - HEAD_CLOTH_AVALON
      - HEAD_CLOTH_ROYAL

  - name: sandalias_tela
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/tela/sandalias]
    template_keys:
      - SHOES_CLOTH_SET1
      - SHOES_CLOTH_SET2
      - SHOES_CLOTH_SET3
      - SHOES_CLOTH_KEEPER
      - SHOES_CLOTH_HELL
      - SHOES_CLOTH_MORGANA
      - SHOES_CLOTH_FEY
      - SHOES_CLOTH_AVALON
      - SHOES_CLOTH_ROYAL

  # Armadura - Cuero
  - name: chaquetas_cuero
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/cuero/chaquetas]
    template_keys:
      - ARMOR_LEATHER_SET1
      - ARMOR_LEATHER_SET2
      - ARMOR_LEATHER_SET3
      - ARMOR_LEATHER_MORGANA
      - ARMOR_LEATHER_HELL
      - ARMOR_LEATHER_UNDEAD
      - ARMOR_LEATHER_FEY
      - ARMOR_LEATHER_AVALON
      - ARMOR_LEATHER_ROYAL

  - name: zapatos_cuero
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/cuero/zapatos]
    template_keys:
      - SHOES_LEATHER_SET1
      - SHOES_LEATHER_SET2
      - SHOES_LEATHER_SET3
      - SHOES_LEATHER_MORGANA
      - SHOES_LEATHER_HELL
      - SHOES_LEATHER_UNDEAD
      - SHOES_LEATHER_FEY
      - SHOES_LEATHER_AVALON
      - SHOES_LEATHER_ROYAL

  - name: capuchas_cuero
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/cuero/capuchas]
    template_keys:
      - HEAD_LEATHER_SET1
      - HEAD_LEATHER_SET2
      - HEAD_LEATHER_SET3
      - HEAD_LEATHER_MORGANA
      - HEAD_LEATHER_HELL
      - HEAD_LEATHER_UNDEAD
      - HEAD_LEATHER_FEY
      - HEAD_LEATHER_AVALON
      - HEAD_LEATHER_ROYAL

  # Armadura - Placas
  - name: armaduras_placas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/placas/armaduras]
    template_keys:
      - ARMOR_PLATE_SET1
      - ARMOR_PLATE_SET2
      - ARMOR_PLATE_SET3
      - ARMOR_PLATE_UNDEAD
      - ARMOR_PLATE_HELL
      - ARMOR_PLATE_KEEPER
      - ARMOR_PLATE_FEY
      - ARMOR_PLATE_AVALON
      - ARMOR_PLATE_ROYAL

  - name: botas_placas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/placas/botas]
    template_keys:
      - SHOES_PLATE_SET1
      - SHOES_PLATE_SET2
      - SHOES_PLATE_SET3
      - SHOES_PLATE_UNDEAD
      - SHOES_PLATE_HELL
      - SHOES_PLATE_KEEPER
      - SHOES_PLATE_FEY
      - SHOES_PLATE_AVALON
      - SHOES_PLATE_ROYAL

  - name: cascos_placas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armadura/placas/cascos]
    template_keys:
      - HEAD_PLATE_SET1
      - HEAD_PLATE_SET2
      - HEAD_PLATE_SET3
      - HEAD_PLATE_UNDEAD
      - HEAD_PLATE_HELL
      - HEAD_PLATE_KEEPER
      - HEAD_PLATE_FEY
      - HEAD_PLATE_AVALON
      - HEAD_PLATE_ROYAL

  # Secundarias (offhands)
  - name: secundarias_mago
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/secundarias/mago]
    template_keys:
      - OFF_BOOK
      - OFF_ORB_MORGANA
      - OFF_DEMONSKULL_HELL
      - OFF_TOTEM_KEEPER
      - OFF_CENSER_AVALON

  - name: secundarias_guerrero
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/secundarias/guerrero]
    template_keys:
      - OFF_SHIELD
      - OFF_TOWERSHIELD_UNDEAD
      - OFF_SHIELD_HELL
      - OFF_SPIKEDSHIELD_MORGANA
      - OFF_SHIELD_AVALON

  - name: secundarias_cazador
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/armas/secundarias/cazador]
    template_keys:
      - OFF_TORCH
      - OFF_HORN_KEEPER
      - OFF_TALISMAN_AVALON
      - OFF_LAMP_UNDEAD
      - OFF_JESTERCANE_HELL

  # Accesorios
  - name: bolsas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/accesorios/bolsas]
    template_keys:
      - BAG
      - BAG_INSIGHT

  - name: capas
    <<: *TIERED_EQUIPMENT
    categories: [equipamiento/accesorios/capas]
    template_keys:
      - CAPE
      - CAPEITEM_FW_BRIDGEWATCH
      - CAPEITEM_FW_FORTSTERLING
      - CAPEITEM_FW_LYMHURST
      - CAPEITEM_FW_MARTLOCK
      - CAPEITEM_FW_THETFORD
      - CAPEITEM_FW_CAERLEON
      - CAPEITEM_FW_BRECILIEN
      - CAPEITEM_AVALON
      - CAPEITEM_SMUGGLER
      - CAPEITEM_HERETIC
      - CAPEITEM_UNDEAD
      - CAPEITEM_KEEPER
      - CAPEITEM_MORGANA
      - CAPEITEM_DEMON

# (Opcional) puedes seguir soportando el formato viejo:
templates: []
